/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1programacion2;

/**
 *
 * @author LENOVO
 */
public class AdministracionEventos extends javax.swing.JFrame {

    /**
     * Creates new form AdministracionEventos
     */
    public AdministracionEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreacionEvento = new javax.swing.JToggleButton();
        EliminarEvento = new javax.swing.JToggleButton();
        EditarEvento = new javax.swing.JToggleButton();
        VerEvento = new javax.swing.JToggleButton();
        BotonVolverMenu = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreacionEvento.setText("Creacion Eventos");
        CreacionEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreacionEventoActionPerformed(evt);
            }
        });

        EliminarEvento.setText("Eliminar un Evento");
        EliminarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEventoActionPerformed(evt);
            }
        });

        EditarEvento.setText("Editar un Evento");
        EditarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEventoActionPerformed(evt);
            }
        });

        VerEvento.setText("Ver Evento");
        VerEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEventoActionPerformed(evt);
            }
        });

        BotonVolverMenu.setText("Volver al Menu Principal");
        BotonVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonVolverMenu)
                    .addComponent(VerEvento)
                    .addComponent(EditarEvento)
                    .addComponent(EliminarEvento)
                    .addComponent(CreacionEvento))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(CreacionEvento)
                .addGap(18, 18, 18)
                .addComponent(EliminarEvento)
                .addGap(18, 18, 18)
                .addComponent(EditarEvento)
                .addGap(18, 18, 18)
                .addComponent(VerEvento)
                .addGap(18, 18, 18)
                .addComponent(BotonVolverMenu)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreacionEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreacionEventoActionPerformed
        CrearEventos lea=new CrearEventos();
        lea.setVisible(true);
        
    }//GEN-LAST:event_CreacionEventoActionPerformed

    private void EliminarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEventoActionPerformed
        EliminarUnEvento elim=new EliminarUnEvento();
        elim.setVisible(true);
    }//GEN-LAST:event_EliminarEventoActionPerformed

    private void EditarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEventoActionPerformed
        // TODO add your handling code here:
        EditarUnEvento edit=new EditarUnEvento();
        edit.setVisible(true);
    }//GEN-LAST:event_EditarEventoActionPerformed

    private void VerEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEventoActionPerformed
        // TODO add your handling code here:
        VerEvento event=new VerEvento();
        event.setVisible(true);
    }//GEN-LAST:event_VerEventoActionPerformed

    private void BotonVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverMenuActionPerformed
        MenuPrincipal menu=new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_BotonVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonVolverMenu;
    private javax.swing.JToggleButton CreacionEvento;
    private javax.swing.JToggleButton EditarEvento;
    private javax.swing.JToggleButton EliminarEvento;
    private javax.swing.JToggleButton VerEvento;
    // End of variables declaration//GEN-END:variables
}
